# Generated by Django 5.2.12 on 2026-05-06 01:02

import chargeback.domain.value_objects.status_contestacao
import chargeback.domain.value_objects.tipo_anexo
import chargeback.domain.value_objects.tipo_contestacao
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='ContestacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.SmallIntegerField(choices=[(chargeback.domain.value_objects.tipo_contestacao.EnumTipoContestacao['NAO_RECONHECIMENTO'], 'Não Reconhecimento'), (chargeback.domain.value_objects.tipo_contestacao.EnumTipoContestacao['PRODUTO_NAO_ENTREGUE'], 'Produto Não Entregue'), (chargeback.domain.value_objects.tipo_contestacao.EnumTipoContestacao['PRODUTO_DIVERGENTE'], 'Produto Divergente'), (chargeback.domain.value_objects.tipo_contestacao.EnumTipoContestacao['CANCELAMENTO_NAO_PROCESSADO'], 'Cancelamento Não Processado'), (chargeback.domain.value_objects.tipo_contestacao.EnumTipoContestacao['COBRANCA_DUPLICADA'], 'Cobrança Duplicada')])),
                ('token_transacao', models.CharField(max_length=255, verbose_name='Token da transação')),
                ('status', models.SmallIntegerField(choices=[(chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['ABERTO'], 'Aberto'), (chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['EM_ANALISE'], 'Em Análise'), (chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['EM_DISPUTA'], 'Em Disputa'), (chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['REABERTO'], 'Reaberto'), (chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['ENCERRADO_COM_PERDA'], 'Encerrado com Perda'), (chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['ENCERRADO_COM_GANHO'], 'Encerrado com Ganho')], default=chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['ABERTO'], verbose_name='Status da contestação')),
                ('produto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Produto')),
                ('bandeira', models.CharField(max_length=255, verbose_name='Bandeira do cartão')),
                ('descricao', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição da contestação')),
                ('data_limite', models.DateTimeField(blank=True, null=True, verbose_name='Data limite da etapa')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargeback.clientemodel')),
            ],
            options={
                'verbose_name': 'Contestação',
                'verbose_name_plural': 'Contestações',
            },
        ),
        migrations.CreateModel(
            name='AnexoContestacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.SmallIntegerField(choices=[(chargeback.domain.value_objects.tipo_anexo.EnumTipoAnexos['COMPROVANTE_ENTREGA'], 'Comprovante de Entrega'), (chargeback.domain.value_objects.tipo_anexo.EnumTipoAnexos['IP_TRANSACAO'], 'IP da Transação'), (chargeback.domain.value_objects.tipo_anexo.EnumTipoAnexos['ASSINATURA_DIGITAL'], 'Assinatura Digital'), (chargeback.domain.value_objects.tipo_anexo.EnumTipoAnexos['REGRISTRO_COMUNICACAO'], 'Registro de Comunicação'), (chargeback.domain.value_objects.tipo_anexo.EnumTipoAnexos['POLITICA_CANCELAMENTO'], 'Política de Cancelamento')], verbose_name='Tipo do anexo')),
                ('observacao', models.TextField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('url', models.URLField(max_length=255, verbose_name='URL do anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargeback.contestacaomodel')),
            ],
            options={
                'verbose_name': 'Anexo de Contestação',
                'verbose_name_plural': 'Anexos de Contestação',
            },
        ),
        migrations.CreateModel(
            name='HistoricoContestacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['ABERTO'], 'Aberto'), (chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['EM_ANALISE'], 'Em Análise'), (chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['EM_DISPUTA'], 'Em Disputa'), (chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['REABERTO'], 'Reaberto'), (chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['ENCERRADO_COM_PERDA'], 'Encerrado com Perda'), (chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['ENCERRADO_COM_GANHO'], 'Encerrado com Ganho')], verbose_name='Status da contestacao')),
                ('observacao', models.TextField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('data_limite', models.DateTimeField(blank=True, null=True, verbose_name='Data limite da etapa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contestacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargeback.contestacaomodel')),
            ],
            options={
                'verbose_name': 'Histórico da Contestação',
                'verbose_name_plural': 'Histórico das Contestações',
            },
        ),
        migrations.CreateModel(
            name='PrazoEtapaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandeira', models.CharField(max_length=50)),
                ('status', models.SmallIntegerField(choices=[(chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['ABERTO'], 'Aberto'), (chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['EM_ANALISE'], 'Em Análise'), (chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['EM_DISPUTA'], 'Em Disputa'), (chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['REABERTO'], 'Reaberto'), (chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['ENCERRADO_COM_PERDA'], 'Encerrado com Perda'), (chargeback.domain.value_objects.status_contestacao.EnumStatusContestacao['ENCERRADO_COM_GANHO'], 'Encerrado com Ganho')])),
                ('dias_prazo', models.PositiveSmallIntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prazo por Etapa',
                'verbose_name_plural': 'Prazos por Etapa',
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('bandeira', 'status'), name='uniq_prazo_bandeira_status_ativo')],
            },
        ),
        migrations.AddIndex(
            model_name='contestacaomodel',
            index=models.Index(fields=['token_transacao', 'tipo'], name='chargeback__token_t_f8f630_idx'),
        ),
        migrations.AddIndex(
            model_name='contestacaomodel',
            index=models.Index(fields=['status', 'ativo'], name='chargeback__status_53a099_idx'),
        ),
        migrations.AddConstraint(
            model_name='contestacaomodel',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('token_transacao', 'tipo'), name='uniq_contestacao_token_tipo_ativo'),
        ),
    ]
